Feature/updated all api endpoints
tfxor/terrahub pull request #1072
Opened 2021-02-11 15:48 UTC by euliancom

## Description
- updated all api endpoints

## Type of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## How Has This Been Tested?
- localhost

### Test Configuration
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-11 15:59 UTC, vcalmic approved these changes

2021-02-11 15:59 UTC, eistrati requested changes

2021-02-11 15:59 UTC, eistrati commented on bin/cli.js
> +
remove space

2021-02-11 15:59 UTC, eistrati commented on src/helpers/wrappers/terrahub.js
> +
remove space

2021-02-15 15:33 UTC, vcalmic approved these changes

2021-02-16 14:09 UTC, eistrati approved these changes

2021-02-16 14:09 UTC, merged